
version: '3.1'

services:

  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
    env_file: .env
